---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.6.3
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: true
    checksum: true
    download: true
    fetch: true
    git: false
    github: true
    gpg: true
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: false
app_desc: An infrastructure as code tool that lets you define both cloud and on-prem
    resources in human-readable configuration files that you can version, reuse, and
    share.
app_name: tofu
app_repo: https://github.com/opentofu/opentofu
app_type: standalone
app_website: https://opentofu.org
archive_conf_path: ''
archive_conf_strip: 0
archive_enabled: true
archive_regex: (\\.tar\\.gz|\\.tgz|\\.zip)$
checksum_conf_algorithm: 256
checksum_enabled: true
checksum_url: https://github.com/opentofu/opentofu/releases/download/v{version}/tofu_{version}_SHA256SUMS
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/opentofu/opentofu/releases/download/v{version}/tofu_{version}_{os}_{arch}.tar.gz
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    tofu: bin/tofu
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-opentofu
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-opentofu.git
source_enabled: false
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    i386: '386'
    i686: '386'
    x86: '386'
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
